= Sample "RTuinOS" - A concept prove of kernelBuilder
:Author:    Peter Vranken 
:Email:     mailto:Peter_Vranken@Yahoo.de
:toc:       left
:xrefstyle: short
:numbered:

== About this sample

This sample is a proof of concept for package
https://github.com/PeterVranken/TRK-USB-MPC5643L/tree/master/LSM/kernelBuilder[kernelBuilder].
RTuinOS, the event controlled real time operating system for Arduino, has
been migrated for the e200z4 core and all original RTuinOS samples run on
the TRK-USB-MPC5643L evaluation board. RTuinOS make use of kernel
interrupts, which cause task switches and system calls for suspending
tasks or for resuming them by sending events.

RTuinOS consists of the source code folder `code\RTOS` (kernelBuilder is
contained). To make it run on the evaluation board the known folder
`code\startup` is required. All samples use console output and they share
the implementation of the serial interface in folder `code\serial`. Folder
`code\common` contains the C entry point `main()`, which is designed such
that the application code gets an environment similar to the original
Arduino board.

The folders in folder `code\applications` contain a sample application of
RTuinOS each. Besides demonstrating the use of RTuinOS, they are
considered test cases for the kernel -- which explains the name `tc<n>`.

The build and debug scripts are a bit different to what you know from the
other samples. They take an argument to select an application to compile;
RTuinOS itself is an infra-structure only, it is not a self-contained,
flashable executable, you always need to compile it together with some
client code.

To see how the sample works you need to open a terminal software on your
host machine. You can find a terminal as part of the CodeWarrior Eclipse
IDE; go to the menu, "Window/Show View/Other/Terminal/Terminal".

Open the serial port, which is offered by the TRK-USB-MPC5643L. (On
Windows, open the Computer Management and go to the Device Manager to find
out.) The Baud rate has been selected as 115200 Bd in file
`code\common\mai_main.c`, 8 Bit, no parity, 1 start and stop Bit. The
sequence \r\n is used as end of line character. The terminal should print
the messages, which are regularly sent by the sample code running on the
evaluation board.

=== RTuinOS

RTuinOS as such is not in the focus of this project. It is an Arduino
project and you can refer to it's
https://sourceforge.net/projects/rtuinos/[original location]. The
documentation is distributed as
https://github.com/PeterVranken/TRK-USB-MPC5643L/tree/master/LSM/RTuinOS/doc/manual/RTuinOS-1.0-UserGuide.pdf[PDF manual].

The manual has not been edited with respect to the differences due to the
e200z4 and board migration. To a small extend, the source code
documentation of the sample applications highlights the made changes but
most of the documentation has not been reworked so that you will still
find remarks about Arduino specifics. It is not planned to edit the manual
or rework the code documentation in the future.

=== Book E versus VLE

The implementation of RTuinOS is not specific to one of the instruction
sets. However, as of writing, its foundation kernelBuilder is not yet
available in VLE assembler and the project setup is done for Book E.

== Tools

=== Environment

==== Command line based build

The makefiles and related scripts require a few settings of the
environment in the host machine. In particular, the location of the GNU
compiler installation needs to be known and the PATH variable needs to
contain the paths to the required tools. 

For Windows users there is a shortcut to PowerShell in the root of this
project (not sample), which opens the shell with the prepared environment.
Furthermore, it creates an alias to the appropriate GNU make executable.
You can simply type `make` from any location to run MinGW32 GNU make.

The PowerShell process reads the script `setEnv.ps1`, located in the
project root, too, to configure the environment. This script requires
configuration prior to its first use. Windows users open it in a text
editor and follow the given instructions that are marked by TODO tags.
Mainly, it's about specifying the installation directory of GCC.

Non-Windows users will read this script to see, which (few) environmental
settings are needed to successfully run the build and prepare an according
script for their native shell.

==== Eclipse for building, flashing and debugging

Flashing and debugging is always done using the NXP CodeWarrior Eclipse
IDE, which is available for free download. If you are going to run the
application build from Eclipse, too, then the same environmental settings
as described above for a shell based build need to be done for Eclipse. The
easiest way to do so is starting Eclipse from a shell, that has executed
the script `setEnv.ps1` prior to opening Eclipse.

For Windows users the script `CW-IDE.ps1` has been prepared. This script
requires configuration prior to its first use. Windows users open it in a
text editor and follow the given instructions that are marked by TODO
tags. Mainly, it's about specifying the installation directory of
CodeWarrior.

Non-Windows users will read this script to see, which (few) environmental
and path settings are needed to successfully run the build under control
of Eclipse and prepare an according script for their native shell.

Once everything is prepared, the CodeWarrior Eclipse IDE will never be
started other than by clicking the script `CW-IDE.ps1` or its equivalent
on non-Windows hosts.

See https://github.com/PeterVranken/TRK-USB-MPC5643L[project overview] and
https://github.com/PeterVranken/TRK-USB-MPC5643L/wiki/Tools-and-Installation[GitHub
Wiki] for more details about downloading and installing the required
tools.

=== Compiler and makefile

Compilation and linkage are makefile controlled. The compiler is GCC
(MinGW-powerpc-eabivle-4.9.4). The makefile is made generic and can be
reused for other projects, not only for a tiny "Hello World" with a few
source files. It supports a number of options (targets); get an overview
by typing:
 
    cd <projectRoot>/LSM/kernelBuilder
    mingw32-make help

The main makefile `GNUmakefile` has been configured for the build of
sample "RTuinOS" but the kernel can't be linked to a runnable binary
without an application. You need to specify the name of an RTuinOS
application on the command line of make. Set variable APP to do so. Type
("tc01" is just an example):

    mingw32-make -s build APP=tc01
    mingw32-make -s build APP=tc01 CONFIG=PRODUCTION

to produce the flashable files
`bin\ppc\tc01\DEBUG\TRK-USB-MPC5643L-RTuinOS-tc01.elf` 
and
`bin\ppc\tc01\PRODUCTION\TRK-USB-MPC5643L-RTuinOS-tc01.elf`.

To get more information, type:

    mingw32-make help

NOTE: The makefile requires the MinGW port of the make processor. The Cygwin
port will fail with obscure, misleading error messages. It's safe to use
the `make.exe` from the compiler installation archive. The makefile is
designed to run on different host systems but has been tested with Windows
7 only.

=== Flashing and debugging

The sample code can be flashed and debugged with the CodeWarrior IDE.

To flash the `*.elf` file of an RTuinOS application like `tc01`, open the
CodeWarrior IDE, go to the menu, click "Window/Show
View/Other/Debug/Debugger Shell". In the debugger shell window, type:

    cd <rootFolderOfSample>/makefile/debugger
    set APP tc01
    source flashDEBUG.tcl
    
or

    set APP tc01
    source flashPRODUCTION.tcl

(Setting TCL variable APP doesn't need to repeated prior to every repeated
flashing.)

The debugger is started by a click on the black triangle next to the blue
icon "bug", then click "Debug Configurations.../CodeWarrior/RTuinOS tc01
(DEBUG)". Confirm and start the debugger with a last click on button
"Debug".

(Or select the according debug configuration for another RTuinOS application.)

You can find more details on using the CodeWarrior IDE at
https://github.com/PeterVranken/TRK-USB-MPC5643L/wiki/Tools-and-Installation.

== Code architecture

This sample builds on sample "kernelBuilder" located in a sibling folder.
"RTuinOS" is compiled for the Book E instruction set. All build settings
and the software architecture are identical to "kernelBuilder". Please refer to
https://github.com/PeterVranken/TRK-USB-MPC5643L/blob/master/LSM/kernelBuilder/readMe.adoc[LSM/kernelBuilder/readMe.adoc]
for details.
