= Sample "printf" - Use of RS 232 serial interface for C's printf & Co.
:Author:    Peter Vranken
:Email:     mailto:Peter_Vranken@Yahoo.de
:Revision:  1
:toc:       left
:numbered:

== About this sample

TODOC Add introduction. Most of the sections below will still apply but
they are irrelevant in the context of this sample and should be revised.

== Tools

=== Environment

==== Command line based build

The makefiles and related scripts require a few settings of the
environment in the host machine. In particular, the location of the GNU
compiler installation needs to be known and the PATH variable needs to
contain the paths to the required tools. 

For Windows users there is a shortcut to PowerShell in the root of this
project (not sample), which opens the shell with the prepared environment.
Furthermore, it creates an alias to the appropriate GNU make executable.
You can simply type `make` from any location to run MinGW32 GNU make.

The PowerShell process reads the script `setEnv.ps1`, located in the
project root, too, to configure the environment. This script requires
configuration prior to its first use. Windows users open it in a text
editor and follow the given instructions that are marked by TODO tags.
Mainly, it's about specifying the installation directory of GCC.

Non-Windows users will read this script to see, which (few) environmental
settings are needed to successfully run the build and prepare an according
script for their native shell.

==== Eclipse for building, flashing and debugging

Flashing and debugging is always done using the NXP CodeWarrior Eclipse
IDE, which is available for free download. If you are going to run the
application build from Eclipse, too, then the same environmental settings
as decribed above for a shell based build need to be done for Eclipse. The
easiest way to do so is starting Eclipse from a shell, that has executed
the script `setEnv.ps1` prior to opening Eclipse.

For Windows users the script `CW-IDE.ps1` has been prepared. This script
requires configuration prior to its first use. Windows users open it in a
text editor and follow the given instructions that are marked by TODO
tags. Mainly, it's about specifying the installation directory of
CodeWarrior.

Non-Windows users will read this script to see, which (few) environmental
and path settings are needed to successfully run the build under control
of Eclipse and prepare an according script for their native shell.

Once everything is prepared, the CodeWarrior Eclipse IDE will never be
started other than by clicking the script `CW-IDE.ps1` or its equivalent
on non-Windows hosts.


=== Compiler and Debugger

The sample is compiled with GCC (MinGW-powerpc-eabivle-4.9.4) and it can
be flashed and debugged with the CodeWarrior IDE. (See project overview
for more details.)

=== Makefile

Compilation and linkage are makefile controlled. The makefile supports a
number of options (targets); get an overview by typing:
 
    cd <projectRoot>/LSM/printf
    mingw32-make help

The main makefile `GNUmakefile` has been configured for the build of
sample "printf". Type:

    mingw32-make -s build 

to produce the flashable file (`TRK-USB-MPC5643L-printf.elf`).

NOTE: The makefile requires the MinGW port of the make processor. The Cygwin
port will fail with obscure, misleading error messages. It's safe to use
the `make.exe` from the compiler installation archive. The makefile is
designed to run on different host systems but has been tested with Windows
7 only.

This sample builds on the basic sample "startup" located in a sibling folder. 
"printf" is compiled for the Book E instruction set. All build settings
and the software architecture are identical to "startup". Please refer to
https://github.com/PeterVranken/TRK-USB-MPC5643L/blob/master/LSM/startup/readMe.adoc
for details.